[package]
name = "anise"
version = "0.1.0"
edition = "2018"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "A high-fidelity space mission toolkit, with orbit propagation, estimation and some systems engineering"
homepage = "https://github.com/anise-toolkit/"
documentation = "https://docs.rs/anise/"
repository = "https://github.com/anise-toolkit/anise.rs"
keywords = ["attitude","navigation","instrument", "spacecraft", "ephemeris"]
categories = ["science", "simulation"]
readme = "README.md"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
hifitime = "3.0.0"
memmap2 = "0.5.0"
crc32fast = "1.3.0"
# der = {version = "0.5.1", features = ["derive", "alloc"]}
# der = {path = "/home/chris/Workspace/rust/formats/der"}
der = { git = "https://github.com/RustCrypto/formats.git", commit = "0dca45e8e3b542582a9bc4f51af7605d4e871337", features = ["derive"]}